import type { Preset, Typography, Decoration, Padding } from '@/lib/types';
import {
  DARK_BOLD_COLORS,
  DARK_BLUE_COLORS,
  DARK_RED_COLORS,
  DARK_GREEN_COLORS,
  DARK_PURPLE_COLORS,
  MESH_DARK_COLORS,
  DARK_MINIMAL_COLORS,
  LIGHT_MINIMAL_COLORS,
  LIGHT_GRAY_COLORS,
  LIGHT_CREAM_COLORS,
  GOV_COLORS,
  YOUTH_COLORS,
  FINANCE_COLORS,
  BEAUTY_COLORS,
  TECH_COLORS,
  FOOD_COLORS,
} from './colors';

const FONT = 'Pretendard, system-ui, sans-serif';

const baseTypo: Typography = {
  fontFamily: FONT,
  headlineWeight: 800,
  headlineSize: 96,
  bodySize: 30,
  headlineLetterSpacing: '-0.03em',
  lineHeight: 1.2,
  headlineUppercase: false,
};

const baseDeco: Decoration = {
  badgeStyle: 'pill',
  cornerRadius: 12,
  accentBar: 'none',
  backgroundPattern: 'none',
  imageTreatment: 'normal',
  shadow: false,
  topLine: false,
  bottomCircle: false,
};

const basePadding: Padding = { top: 100, right: 100, bottom: 120, left: 100 };

export const STYLE_PRESETS: Preset[] = [
  {
    id: 'preset-dark-bold',
    name: '다크 볼드',
    category: 'style',
    description: '검정 + 네온, 강렬한 임팩트',
    layout: 'dark-bold',
    colorVariants: DARK_BOLD_COLORS,
    typography: { ...baseTypo, headlineWeight: 900, headlineSize: 108, lineHeight: 1.05 },
    decoration: { ...baseDeco, badgeStyle: 'square', cornerRadius: 6, shadow: true },
    padding: basePadding,
    builtin: true,
  },
  {
    id: 'preset-dark-blue',
    name: '다크 블루',
    category: 'style',
    description: '네이비 + 시안, 신뢰감',
    layout: 'dark-blue',
    colorVariants: DARK_BLUE_COLORS,
    typography: { ...baseTypo, headlineWeight: 800, headlineSize: 96 },
    decoration: { ...baseDeco, badgeStyle: 'pill', cornerRadius: 20, shadow: true },
    padding: basePadding,
    builtin: true,
  },
  {
    id: 'preset-dark-red',
    name: '다크 레드',
    category: 'style',
    description: '버건디 + 오렌지, 강한 주목',
    layout: 'dark-red',
    colorVariants: DARK_RED_COLORS,
    typography: { ...baseTypo, headlineWeight: 900, headlineSize: 100, lineHeight: 1.1 },
    decoration: { ...baseDeco, badgeStyle: 'square', cornerRadius: 8, shadow: true },
    padding: basePadding,
    builtin: true,
  },
  {
    id: 'preset-dark-green',
    name: '다크 그린',
    category: 'style',
    description: '포레스트 + 라임, 자연',
    layout: 'dark-green',
    colorVariants: DARK_GREEN_COLORS,
    typography: { ...baseTypo, headlineWeight: 800, headlineSize: 96 },
    decoration: { ...baseDeco, badgeStyle: 'pill', cornerRadius: 24, shadow: true },
    padding: basePadding,
    builtin: true,
  },
  {
    id: 'preset-dark-purple',
    name: '다크 퍼플',
    category: 'style',
    description: '보라 + 핑크, 감성적',
    layout: 'dark-purple',
    colorVariants: DARK_PURPLE_COLORS,
    typography: { ...baseTypo, headlineWeight: 800, headlineSize: 96 },
    decoration: { ...baseDeco, badgeStyle: 'pill', cornerRadius: 32, shadow: true },
    padding: basePadding,
    builtin: true,
  },
  {
    id: 'preset-mesh-dark',
    name: '메시 다크',
    category: 'style',
    description: '그라데이션 메시, 세련된 느낌',
    layout: 'mesh-dark',
    colorVariants: MESH_DARK_COLORS,
    typography: { ...baseTypo, headlineWeight: 900, headlineSize: 104, lineHeight: 1.1 },
    decoration: {
      ...baseDeco,
      badgeStyle: 'pill',
      cornerRadius: 999,
      backgroundPattern: 'mesh',
      shadow: true,
    },
    padding: basePadding,
    builtin: true,
  },
  {
    id: 'preset-dark-minimal',
    name: '다크 미니멀',
    category: 'style',
    description: '차콜 + 화이트, 세련된 최소주의',
    layout: 'dark-minimal',
    colorVariants: DARK_MINIMAL_COLORS,
    typography: {
      ...baseTypo,
      headlineWeight: 700,
      headlineSize: 88,
      headlineLetterSpacing: '-0.02em',
    },
    decoration: {
      ...baseDeco,
      badgeStyle: 'underline',
      cornerRadius: 0,
      topLine: true,
    },
    padding: { top: 120, right: 110, bottom: 130, left: 110 },
    builtin: true,
  },
  {
    id: 'preset-light-minimal',
    name: '라이트 미니멀',
    category: 'style',
    description: '흰 배경 + 검정, 클래식',
    layout: 'light-minimal',
    colorVariants: LIGHT_MINIMAL_COLORS,
    typography: { ...baseTypo, headlineWeight: 800, headlineSize: 92 },
    decoration: {
      ...baseDeco,
      badgeStyle: 'underline',
      cornerRadius: 0,
      topLine: true,
    },
    padding: basePadding,
    builtin: true,
  },
  {
    id: 'preset-light-gray',
    name: '라이트 그레이',
    category: 'style',
    description: '연회색 + 네이비, 차분한',
    layout: 'light-gray',
    colorVariants: LIGHT_GRAY_COLORS,
    typography: { ...baseTypo, headlineWeight: 800, headlineSize: 92 },
    decoration: { ...baseDeco, badgeStyle: 'pill', cornerRadius: 16 },
    padding: basePadding,
    builtin: true,
  },
  {
    id: 'preset-light-cream',
    name: '라이트 크림',
    category: 'style',
    description: '베이지 + 브라운, 따뜻한',
    layout: 'light-cream',
    colorVariants: LIGHT_CREAM_COLORS,
    typography: { ...baseTypo, headlineWeight: 800, headlineSize: 92 },
    decoration: {
      ...baseDeco,
      badgeStyle: 'pill',
      cornerRadius: 24,
      backgroundPattern: 'noise',
    },
    padding: basePadding,
    builtin: true,
  },
];

export const INDUSTRY_PRESETS: Preset[] = [
  {
    ...STYLE_PRESETS[7],
    id: 'ind-gov',
    name: '정부지원금',
    category: 'industry',
    description: '신뢰감 있는 블루',
    colorVariants: GOV_COLORS,
  },
  {
    ...STYLE_PRESETS[7],
    id: 'ind-youth',
    name: '청년지원',
    category: 'industry',
    description: '희망찬 그린',
    colorVariants: YOUTH_COLORS,
  },
  {
    ...STYLE_PRESETS[0],
    id: 'ind-finance',
    name: '재테크',
    category: 'industry',
    description: '다크 + 골드',
    colorVariants: FINANCE_COLORS,
  },
  {
    ...STYLE_PRESETS[4],
    id: 'ind-beauty',
    name: '뷰티',
    category: 'industry',
    description: '소프트 핑크',
    colorVariants: BEAUTY_COLORS,
  },
  {
    ...STYLE_PRESETS[1],
    id: 'ind-tech',
    name: 'IT/테크',
    category: 'industry',
    description: '다크 + 시안',
    colorVariants: TECH_COLORS,
  },
  {
    ...STYLE_PRESETS[5],
    id: 'ind-food',
    name: '맛집',
    category: 'industry',
    description: '따뜻한 오렌지',
    colorVariants: FOOD_COLORS,
  },
];

export const ALL_BUILTIN_PRESETS = [...STYLE_PRESETS, ...INDUSTRY_PRESETS];

export function getPresetById(id: string, customPresets: Preset[] = []): Preset {
  const found = [...ALL_BUILTIN_PRESETS, ...customPresets].find((p) => p.id === id);
  return found || STYLE_PRESETS[0];
}