import type { Preset, Typography, Decoration } from '@/lib/types';

const typo = (fontFamily: string, overrides: Partial<Typography> = {}): Typography => ({
  fontFamily,
  headlineWeight: 800,
  headlineSize: 96,
  bodySize: 34,
  headlineLetterSpacing: '-0.03em',
  lineHeight: 1.2,
  ...overrides,
});

const deco = (overrides: Partial<Decoration> = {}): Decoration => ({
  badgeStyle: 'pill',
  cornerRadius: 24,
  accentBar: 'none',
  backgroundPattern: 'none',
  imageTreatment: 'normal',
  shadow: false,
  ...overrides,
});

export const STYLE_PRESETS: Preset[] = [
  {
    id: 'style-minimal',
    name: '미니멀 모던',
    category: 'style',
    description: '깔끔한 흰 배경, 파란 포인트',
    builtin: true,
    theme: {
      id: 'theme-minimal',
      name: '미니멀',
      background: '#ffffff',
      surface: '#f8fafc',
      text: '#0f172a',
      accent: '#2563eb',
      accentSoft: '#dbeafe',
    },
    typography: typo('Pretendard, system-ui, sans-serif'),
    decoration: deco({ badgeStyle: 'pill', cornerRadius: 24 }),
  },
  {
    id: 'style-magazine',
    name: '매거진',
    category: 'style',
    description: '세리프 폰트, 편집숍 느낌',
    builtin: true,
    theme: {
      id: 'theme-magazine',
      name: '매거진',
      background: '#faf7f2',
      surface: '#f0ebe1',
      text: '#1c1917',
      accent: '#9a3412',
      accentSoft: '#fed7aa',
    },
    typography: typo('"Noto Serif KR", serif', {
      headlineWeight: 700,
      headlineSize: 104,
      lineHeight: 1.15,
    }),
    decoration: deco({
      badgeStyle: 'underline',
      cornerRadius: 0,
      accentBar: 'top',
      backgroundPattern: 'noise',
    }),
  },
  {
    id: 'style-dark-neon',
    name: '다크 네온',
    category: 'style',
    description: '어두운 배경, 네온 시안',
    builtin: true,
    theme: {
      id: 'theme-dark-neon',
      name: '다크 네온',
      background: '#0a0a0f',
      surface: '#14141d',
      text: '#f8fafc',
      accent: '#22d3ee',
      accentSoft: '#164e63',
    },
    typography: typo('Pretendard, system-ui, sans-serif', {
      headlineWeight: 900,
      headlineLetterSpacing: '-0.04em',
    }),
    decoration: deco({
      badgeStyle: 'square',
      cornerRadius: 8,
      accentBar: 'left',
      backgroundPattern: 'mesh',
      shadow: true,
    }),
  },
  {
    id: 'style-pastel',
    name: '파스텔',
    category: 'style',
    description: '부드러운 파스텔 톤',
    builtin: true,
    theme: {
      id: 'theme-pastel',
      name: '파스텔',
      background: '#fef6fb',
      surface: '#fce7f3',
      text: '#4c1d3d',
      accent: '#ec4899',
      accentSoft: '#fce7f3',
    },
    typography: typo('"Gowun Dodum", sans-serif', { headlineWeight: 700, headlineSize: 88 }),
    decoration: deco({
      badgeStyle: 'pill',
      cornerRadius: 32,
      backgroundPattern: 'dots',
    }),
  },
  {
    id: 'style-brutalist',
    name: '브루탈리즘',
    category: 'style',
    description: '강한 대비, 굵은 폰트',
    builtin: true,
    theme: {
      id: 'theme-brutalist',
      name: '브루탈리즘',
      background: '#fde047',
      surface: '#fef08a',
      text: '#000000',
      accent: '#dc2626',
      accentSoft: '#fecaca',
    },
    typography: typo('"Black Han Sans", sans-serif', {
      headlineWeight: 400,
      headlineSize: 112,
      lineHeight: 1.05,
    }),
    decoration: deco({
      badgeStyle: 'square',
      cornerRadius: 0,
      accentBar: 'top',
      backgroundPattern: 'grid',
      shadow: true,
    }),
  },
  {
    id: 'style-editorial',
    name: '에디토리얼',
    category: 'style',
    description: '뉴스레터 느낌',
    builtin: true,
    theme: {
      id: 'theme-editorial',
      name: '에디토리얼',
      background: '#ffffff',
      surface: '#f4f4f5',
      text: '#18181b',
      accent: '#059669',
      accentSoft: '#d1fae5',
    },
    typography: typo('"Noto Serif KR", serif', { headlineWeight: 600, headlineSize: 92 }),
    decoration: deco({
      badgeStyle: 'underline',
      cornerRadius: 0,
      accentBar: 'left',
    }),
  },
];

export const INDUSTRY_PRESETS: Preset[] = [
  {
    id: 'ind-gov',
    name: '정부지원금',
    category: 'industry',
    description: '신뢰감 있는 블루',
    builtin: true,
    theme: {
      id: 'theme-gov',
      name: '정부지원',
      background: '#ffffff',
      surface: '#eff6ff',
      text: '#0f172a',
      accent: '#1d4ed8',
      accentSoft: '#dbeafe',
    },
    typography: typo('Pretendard, system-ui, sans-serif'),
    decoration: deco({ badgeStyle: 'pill', cornerRadius: 20 }),
  },
  {
    id: 'ind-youth',
    name: '청년지원',
    category: 'industry',
    description: '희망찬 그린 톤',
    builtin: true,
    theme: {
      id: 'theme-youth',
      name: '청년지원',
      background: '#ffffff',
      surface: '#ecfdf5',
      text: '#064e3b',
      accent: '#10b981',
      accentSoft: '#d1fae5',
    },
    typography: typo('Pretendard, system-ui, sans-serif', { headlineSize: 100 }),
    decoration: deco({ badgeStyle: 'pill', cornerRadius: 28 }),
  },
  {
    id: 'ind-finance',
    name: '재테크',
    category: 'industry',
    description: '다크 + 골드 포인트',
    builtin: true,
    theme: {
      id: 'theme-finance',
      name: '재테크',
      background: '#0f172a',
      surface: '#1e293b',
      text: '#fef3c7',
      accent: '#f59e0b',
      accentSoft: '#78350f',
    },
    typography: typo('Pretendard, system-ui, sans-serif', { headlineLetterSpacing: '-0.04em' }),
    decoration: deco({ badgeStyle: 'square', cornerRadius: 12, accentBar: 'top', shadow: true }),
  },
  {
    id: 'ind-beauty',
    name: '뷰티',
    category: 'industry',
    description: '소프트 핑크 톤',
    builtin: true,
    theme: {
      id: 'theme-beauty',
      name: '뷰티',
      background: '#fff5f8',
      surface: '#ffe4ec',
      text: '#831843',
      accent: '#f43f5e',
      accentSoft: '#ffe4e6',
    },
    typography: typo('"Gowun Dodum", sans-serif', { headlineWeight: 700, headlineSize: 90 }),
    decoration: deco({ badgeStyle: 'pill', cornerRadius: 36, backgroundPattern: 'dots' }),
  },
  {
    id: 'ind-tech',
    name: 'IT/테크',
    category: 'industry',
    description: '다크 + 시안',
    builtin: true,
    theme: {
      id: 'theme-tech',
      name: '테크',
      background: '#020617',
      surface: '#0f172a',
      text: '#e2e8f0',
      accent: '#06b6d4',
      accentSoft: '#164e63',
    },
    typography: typo('Pretendard, system-ui, sans-serif', { headlineLetterSpacing: '-0.04em' }),
    decoration: deco({
      badgeStyle: 'square',
      cornerRadius: 10,
      accentBar: 'left',
      backgroundPattern: 'mesh',
      shadow: true,
    }),
  },
  {
    id: 'ind-food',
    name: '맛집',
    category: 'industry',
    description: '따뜻한 레드/크림',
    builtin: true,
    theme: {
      id: 'theme-food',
      name: '맛집',
      background: '#fffbf5',
      surface: '#fef3c7',
      text: '#431407',
      accent: '#ea580c',
      accentSoft: '#fed7aa',
    },
    typography: typo('"Jua", sans-serif', {
      headlineWeight: 400,
      headlineSize: 100,
      headlineLetterSpacing: '-0.01em',
    }),
    decoration: deco({ badgeStyle: 'pill', cornerRadius: 30, backgroundPattern: 'noise' }),
  },
];

export const ALL_BUILTIN_PRESETS = [...STYLE_PRESETS, ...INDUSTRY_PRESETS];